version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    env_file:
      - .env
    networks:
      - base
    # ports:
    #   - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    # ports:
    #   - 8081:8081
    env_file:
      - .env
    networks:
      - base
  
  api: 
    container_name: latte
    restart: always
    build: ./backend
    env_file:
      - .env
    networks:
      - base
    ports:
      - "3000:3000"

networks:
  base: